### ISSUE TITLE
Remote Filesystem (S3, Azure etc)

### ISSUE THREAD

**Issue by tylerwiegand** [RubixML/ML#104]
The Filesystem class states:
```
Filesystems are local or remote storage drives that are organized by files and folders. The filesystem persister serializes models to a file at a user-specified path.
```
I can't find anything in the documentation about how to use a remote model, for instance: read a model remotely and train it partially OR read a model remotely and perform predictions from it.

I'm considering a project on a serverless platform and won't be able to just download the model like I am currently. Anyone point me in the right direction? Thanks!

**Comment by simplechris** [comment]
You needn't rely on NFS as this can be handled by using php's stream wrappers.

This will enable you to use the existing Rubix Filesystem Persister and refer to files on the remote filesystems as if they were local files (e.g `s3://bucket/key`) once the stream wrapper is registered native php functions like `file_get_contents` and `is_file` all work with the remote references.

Most official SDKs will offer this functionality ([AWS](https://docs.aws.amazon.com/aws-sdk-php/v2/guide/feature-s3-stream-wrapper.html#amazon-s3-stream-wrapper), [Google Cloud](https://github.com/googleapis/google-cloud-php-storage#stream-wrapper) are the ones I have personally used) but it is also trivial to implement your own stream wrappers 👍

**Comment by andrewdalpino** [comment]
Thank you @simplechris for the info, this helps alot!

Do you think it would be nice to offer some "sugar" for the user by offering persisters for S3, Azure, etc. that use stream wrappers under the hood? Or is this best handled on a per case basis by the user?

**Comment by andrewdalpino** [comment]
This feature has been added in 0.3.0 https://github.com/RubixML/RubixML/releases/tag/0.3.0
