### ISSUE TITLE
Integrate persistence subsystem with all the things!!!

### ISSUE THREAD

**Issue by andrewdalpino** [RubixML/ML#108]
Right now, the persistence abstraction is limited to Estimators, however, think of how cool it would be to have them work with *everything*. This could be one of the major enhancements we deliver in the next major release (1.0.0). This ticket is to discuss the design of the new persistence subsystem. The idea is to be able to use Persisters as a one-stop-shop.

The relevant abstractions we current have to work with are:

- [Persisters](https://docs.rubixml.com/en/latest/persisters/api.html) - save and load chunks of encoded data
- [Serailizers](https://github.com/RubixML/RubixML/blob/master/src/Persisters/Serializers/Serializer.php) - turn objects into chunks of encoded data
- [Persistable objects](https://docs.rubixml.com/en/latest/persistable.html) - objects whitelisted for persistence
- [Encoding](https://github.com/RubixML/RubixML/blob/master/src/Encoding.php) - a low-level value object used throughout Rubix to wrap encoded data
- [CSV](https://docs.rubixml.com/en/latest/extractors/csv.html), [JSON](https://docs.rubixml.com/en/latest/extractors/json.html), [NDJSON](https://docs.rubixml.com/en/latest/extractors/ndjson.html) extractors - since they deal with loading encoded data from a file
- [Transformers](https://docs.rubixml.com/en/latest/transformers/api.html) (Stateful and Elastic) - objects we'd like to persist using the persistence subsystem but have not implemented yet

Backwards compatibility breaks are fine since this targets the next major release.

Some place to start ...

We can probably replace any string `$path` arguments on Encoding, CSV, NDJSON, and JSON with a Persister interface instead. It's a little more to type out in the constructor but it's a powerful abstraction. Imagine loading CSV datasets from a Redis database or JSON dataset from a MongoDB database. Or saving a cross-validation report directly to a file on an S3 server in  JSON format.

The Persistable interface is actually just a whitelist marker for "any object that can safely be persisted". It shouldn't be too hard to just have Transformers 'implement' the interface and hop on the persistence train.

**Comment by andrewdalpino** [comment]
I think something else that we should incorporate into this one-persistence-subsystem-to-rule-them-all is a way to store meta data on the persisted object. For example, the method used for serialization, the version number of the class (See https://github.com/RubixML/RubixML/issues/115), and maybe even a checksum.

CC @simplechris @ChristophWurst

**Comment by andrewdalpino** [comment]
So we've solved the pressing issues without having to make breaking changes fortunately ... closing this ticket as the value in integrating everything is becoming less obvious. We'll keep this idea in  mind in case that changes in the future.

**Comment by ChristophWurst** [comment]
Thanks a lot :pray: :rocket:
