### ISSUE TITLE
Avoid persisting empty encoding objects

### ISSUE THREAD

**Issue by simplechris** [RubixML/ML#111]
❓  **Question:** As we are throwing a `RuntimeException` when trying to _read_ an empty encodings, should we also raise a similar exception in the `save` method if trying to _write_ an empty encoding? 🤔

_Originally posted by @simplechris in https://github.com/RubixML/RubixML/pull/109#discussion_r486381555_

**Comment by andrewdalpino** [comment]
Thanks again @simplechris!
