### ISSUE TITLE
Compatibility detection between serialized models after version upgrades

### ISSUE THREAD

**Issue by ChristophWurst** [RubixML/ML#115]
**Is your feature request related to a problem? Please describe.**
Dependabot sent us https://github.com/nextcloud/mail/pull/3610 and I'm a bit hesitant integrating this change because our installations have existing models persisted and it's not obvious for a user of the library whether those have to be discarded or can be reused (class props are still the same in the new version).

For some environments it might be OK to "just" retrain the model before the new code goes into production, but it's not really the case for how we use rubix-ml in Nextcloud Mail. The model is trained in the background, for each user's account. If we discard the model there is a time window where no classification is possible. Some processes rely on this, though, so it would give sub-par UX at best.

**Describe the solution you'd like**
I think it should be technically feasible to have a version number or similar as property of each model. This number is touched (incremented) every time the data structure changes. Then if php successfully deserialized the class you can compare the restored value with the default of a new class. If there's a mismatch, you throw.

**Describe alternatives you've considered**
n/a

**Additional context**
I guess this is somewhat related to https://github.com/RubixML/RubixML/issues/108 and https://github.com/RubixML/RubixML/issues/58

**Comment by andrewdalpino** [comment]
Is "detection" enough to solve your issue @ChristophWurst?

**Comment by andrewdalpino** [comment]
@ChristophWurst @simplechris I like the idea of versioning persistable objects, however, if the serialized data and class property definitions don't match up PHP will ~~throw an exception~~ upon calling `unserialize()`.

EDIT: PHP will happily instantiate the object with null properties or add properties to the definition without warning.

**Comment by ChristophWurst** [comment]
If php can't even unserialize the string then we are out of luck anyway. I'm more worried about the nifty cases where for example a property was nullable before but in the new version of the code it's always assigned a value. Php will (I think) happily unserialize. The resulting object is semantically faulty. Does that make sense?

I did this quick test in two interactive shells:

## Shell 1

```
php > class A {
php {   private $a;
php {   private $b;
php { 
php {   public function __construct() {
php {     $this->a = 3;
php {   }
php { }
php > 
php > $a1 = new A();
php > echo serialize($a1);
O:1:"A":2:{s:4:"Aa";i:3;s:4:"Ab";N;}
php > file_put_contents('/tmp/a.ser', serialize($a1));
```

## Shell 2

```
php > class A {
php {   private $a;
php {   private $b;
php { 
php {   public function __construct() {
php {     $this->a = 4;
php {     $this->b = 2;
php {   }
php { }
php > $a1 = new A();
php > echo serialize($a1);
O:1:"A":2:{s:4:"Aa";i:4;s:4:"Ab";i:2;}
php > $a1ser = file_get_contents('/tmp/a.ser');
php > echo $a1ser;
O:1:"A":2:{s:4:"Aa";i:3;s:4:"Ab";N;}
php > $a1orig = unserialize($a1ser);
php > var_dump($a1orig);
php shell code:1:
class A#2 (2) {
  private $a =>
  int(3)
  private $b =>
  NULL
}
```

As you can see, php happily unserializes the object because no new properties were added. Even worse, I tried with a third shell to see what happens if you add a new property:

```
php > class A {
php {   private $a;
php {   private $b;
php {   private $c;
php { }
php > $a1ser = file_get_contents('/tmp/a.ser');
php > $a1orig = unserialize($a1ser);
php > var_dump($a1orig);
php shell code:1:
class A#1 (3) {
  private $a =>
  int(3)
  private $b =>
  NULL
  private $c =>
  NULL
}
```

So php is quite "flexible" and will just set the new properties to null. There was not an exception because of a mismatching property.

**Comment by andrewdalpino** [comment]
@ChristophWurst yup makes sense, thanks for the information. I've had similar results. Perhaps a solution such as the [ONNX](https://onnx.ai/) format could help us out (implemented as a Serializer). In other words, we live with the imperfections of the Native serializer but provide at least one Serializer implementation (such as ONNX) that *is* version aware and interoperable.

As @simplechris mentioned, we are working on revamping the entire persistence subsystem for version 1.0.0. Maybe we can come up with something if we put our heads together.

**Comment by andrewdalpino** [comment]
What if we put a `$version` property on every Persistable object and compared that to a class constant that we increment everytime the class definition changes? Perhaps this could be done using the new PHP 7.4 `__unserialize()` magic method. If there is no `$version` property (it's null as I believe this would be the behavior of unserializing an object without the version property) then we can assume the version is 0. Also, in some cases where we add a new property to a class (such as a hyper-parameter) we could perhaps insert a default value by checking for nulls in the `__unserialize()`  method. Just throwing ideas out there!

Any thoughts?

**Comment by andrewdalpino** [comment]
Also, this is sorta related. In this commit https://github.com/RubixML/RubixML/commit/59bafb781dd70e03d16c2771551c75c8ef287fb2 we now catch missing class definitions (missing, not semantically faulty like you say) and throw a more helpful exception in both Native and Igbinary serializers.

**Comment by andrewdalpino** [comment]
@ChristophWurst A prototype solution to this can be found in https://github.com/RubixML/ML/pull/158

The idea is a custom file format with metadata and automatically tracking class revisions. Your early feedback would be appreciated!
