### ISSUE TITLE
Better visualization of decision trees (CART)

### ISSUE THREAD

**Issue by andrewdalpino** [RubixML/ML#136]
Currently, our CART implementation offers the `rules()` method which outputs a rules diagram to the terminal that helps the user visualize the tree structure. The diagram uses ASCII characters to represent the nodes of the tree. However, we can go one better by using *actual* graphics. I'm picturing a graph representation with nodes and edges with the root node of the tree at the top and the leaf nodes at the bottom. Each node would be labeled with the column and value it splits on and can include metadata such as the node's purity increase.

I came accross [this](https://github.com/graphp/graphviz) library which may be of service. It's based on Graphviz.

**Comment by andrewdalpino** [comment]
This project or similar projects may be of service to this enhancement

https://github.com/viewi/viewi

**Comment by DrDub** [comment]
I can give this a try.

**Comment by andrewdalpino** [comment]
Hey @DrDub how's it going! Hope you're well ... how would we go about implementing something like this? My initial thought was to generate an HTML page and use like a javascript graph library to create the visualization.

**Comment by DrDub** [comment]
Hi @andrewdalpino, things are going very well. Looking into contributing to Rubix ML.

The approach taken by sklearn and lightgbm is to have two methods: the first one produces a graphviz object and the second produces an image. That way users can save the graphviz file and peruse it as they see fit (running graphviz with different parameters, different graph layout algorithms, resolutions, etc) or they can just inspect the tree at once.

I can start with a CART-to-dot code that will then has no dependencies (as it produces a text file). We can look at the function that produces an image (which will need graphviz) later. What do you think?
