### ISSUE TITLE
What happens when 2 cluster centroids are identical (K-means)?

### ISSUE THREAD

**Issue by halimkun** [RubixML/ML#179]
hi friends, i encountered a problem like this.

i have a dataset like this
8 data with label
3 variables
the csv file looks like this
```
Tanggungan;Pekerjaan;Penghasilan;Label
4;2;3;Label 1
2;1;3;Label 2
2;5;1;Label 3
etc . . .
```

when train with KMeans, with a value of `K = 5`
the output that comes out is only `4` train results

```
object(Rubix\ML\Report)[6]
  protected array 'attributes' => 
    array (size=4)
      0 => 
        array (size=8)
          'Label 1' => int 1
          'Label 2' => int 0
          'Label 3' => int 0
          'Label 4' => int 0
          'Label 5' => int 0
          'Label 6' => int 0
          'Label 7' => int 1
          'Label 8' => int 0
      1 => 
        array (size=8)
          'Label 1' => int 0
          'Label 2' => int 1
          'Label 3' => int 0
          'Label 4' => int 1
          'Label 5' => int 0
          'Label 6' => int 0
          'Label 7' => int 0
          'Label 8' => int 1
      2 => 
        array (size=8)
          'Label 1' => int 0
          'Label 2' => int 0
          'Label 3' => int 1
          'Label 4' => int 0
          'Label 5' => int 0
          'Label 6' => int 0
          'Label 7' => int 0
          'Label 8' => int 0
      4 => 
        array (size=8)
          'Label 1' => int 0
          'Label 2' => int 0
          'Label 3' => int 0
          'Label 4' => int 0
          'Label 5' => int 1
          'Label 6' => int 1
          'Label 7' => int 0
          'Label 8' => int 0
```

my code looks like this
```
$fileName = 'cth-data.csv';
$delimiter = CsvHandle::getFileDelimiter($fileName);

$dataset = Labeled::fromIterator(new CSV($fileName, true, $delimiter))
    ->apply(new NumericStringConverter());

$seeder = [ [4,2,3], [2,1,3], [2,5,1], [2,1,3], [2,3,2] ];
$estimator = new KMeans(5,128,1000,10.0, 1000, new Euclidean(), new Preset($seeder));
$estimator->train($dataset);

$predictions = $estimator->predict($dataset);

$report = new ContingencyTable();
$results = $report->generate($predictions, $dataset->labels());
var_dump($results);
```
> and for example I set `K = 6`
> then the output of generatenya is `only 5`.
> 
> in my case index array 3 was missing.

**I don't know if this is a problem with my coding or what, because I don't really understand KMeans.**

**Comment by andrewdalpino** [comment]
Hi @halimkun :)

What does `$estimator->sizes()` say? Does it show 5 unique cluster centroids? Does one of the clusters have a 0 count?

https://docs.rubixml.com/latest/clusterers/k-means.html#additional-methods

**Comment by halimkun** [comment]
hi guys maybe i just found out the cause of the problem thanks to you.
```
array (size=5)
  0 => int 2
  1 => int 3
  2 => int 1
  3 => int 0
  4 => int 2
```
from from `$estimator->sizes()` shows the value 0 at the 3rd index,
and it turns out that the value of the centroids is the same as the others.

when i tried adding centroids which were all different, it wasn't a problem anymore.

> so in this case, at least we add the correct condition then ?
> Or any other recommendations from you?

**Comment by andrewdalpino** [comment]
Hey @halimkun it sounds like you got it figured out. I didn't notice the duplicate centroid earlier but that would definitely explain why only 4 of the 5 clusters are being assigned.

As a side note, I'm wondering if we should add a check for duplicate centroid seeds.
