### ISSUE TITLE
How to use ML to online game's NPC

### ISSUE THREAD

**Issue by uiosun** [RubixML/ML#191]
I can't write a "flexible and smart" AI-Tree or Finite State Machines, in my RPG online game. so, I find ML lib and submit the issue:

Can I create "monster / caravan / monarch AI" use ML? i think thousands of player can interact to train them.

how to do it? ( has some tutorial by "first step"? )

**Comment by andrewdalpino** [comment]
Hi @Sun-FreePort! By NPC do you mean "non-playable character?"

**Comment by uiosun** [comment]
> Hi @Sun-FreePort! By NPC do you mean "non-playable character?"

Right, `AI = NPC = non-player character`.

(playable or player? i think is non-player)

**Comment by andrewdalpino** [comment]
Ok, great. Let's try to frame the problem as a machine learning one ...

ML is all about making predictions. What are the inputs or outputs to the NPC's logic that you'd like to *predict?* Once we have the predictions then we can have the NPC act on them in some way.

Maybe an example would be ... We'd like to know the probability of an NPC winning in a fight. If the probability is low, then the NPC will run - if the probability is high then NPC whoops some ass.

**Comment by uiosun** [comment]
> Ok, great. Let's try to frame the problem as a machine learning one ...
> 
> ML is all about making predictions. What are the inputs or outputs to the NPC's logic that you'd like to _predict?_ Once we have the predictions then we can have the NPC act on them in some way.
> 
> Maybe an example would be ... We'd like to know the probability of an NPC winning in a fight. If the probability is low, then the NPC will run - if the probability is high then NPC whoops some ass.

Well, nice!

the example, is helpful for me! I 'm going learn ML document and try set some act rule by fight / shopping.

I will report my progress, in there. Thank you! (very very very~  :) )
