### ISSUE TITLE
Auto ML

### ISSUE THREAD

**Issue by jsmmo** [RubixML/ML#36]
Are you working on auto ml features or is it even in the scope this API? 

Some auto tuning features would be a great benefit for the lib.

**Comment by andrewdalpino** [comment]
Hi @jsmmo thanks for the great question

Auto ML is defined as an automated approach to machine learning from end to end. Rubix ML has a number of features that enable the automation of ML processes such as hyper-parameter selection, data transformation, feature selection, and imputation - but we do not go as far as "end-to-end" yet.

For example, Rubix ML currently has a meta-estimator called [Grid Search](https://docs.rubixml.com/en/latest/grid-search.html) that allows you to search through a set of possible hyper-parameters and it will automatically select the best ones based on the validation score they receive

Auto ML is definitely on our radar and you'll probably see more features implemented in the future

Are there any specific Auto ML features that you'd like to see?

This [paper](https://arxiv.org/pdf/1810.13306.pdf) has some great information

**Comment by andrewdalpino** [comment]
Another AutoML feature was added in 0.2.0 called Recursive Feature Eliminator (RFE). This is a supervised feature selector that works with a FeatureRanking learner under the hood.

https://docs.rubixml.com/en/latest/transformers/recursive-feature-eliminator.html

**Comment by andrewdalpino** [comment]
K Best Feature Selector was added in 0.3.0 https://github.com/RubixML/RubixML/releases/tag/0.3.0

As AutoML features are now well integrated with the library, closing this discussion.
