### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by ghost** [RubixML/ML#50]
**Describe the bug**
The Example section on https://docs.rubixml.com/en/latest/regressors/extra-tree-regressor.html states to use the following namespace:
`use Rubix\ML\Classifiers\ExtraTreeRegressor;`

**Expected behavior**
It should state
`use Rubix\ML\Regressors\ExtraTreeRegressor;`

**Comment by andrewdalpino** [comment]
Hi @drankje thanks for the heads up

Would you like to submit the pull request to correct the typo or should I?

**Comment by ghost** [comment]
Sorry for my late response, I've just created a PR for this issue.
