### ISSUE TITLE
Undefined Offset, when making an image prediction

### ISSUE THREAD

**Issue by webciter** [RubixML/ML#56]
ErrorException  : Undefined offset: 4677996

  at /home/ubuntu/environment/vendor/rubix/ml/src/Kernels/Distance/Euclidean.php:43
    39|     {
    40|         $distance = 0.;
    41| 
    42|         foreach ($a as $i => $value) {
  > 43|             $distance += ($value - $b[$i]) ** 2;
    44|         }
    45| 
    46|         return sqrt($distance);
    47|     }

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined offset: 4677996", "/home/ubuntu/environment/vendor/rubix/ml/src/Kernels/Distance/Euclidean.php", [])
      /home/ubuntu/environment/vendor/rubix/ml/src/Kernels/Distance/Euclidean.php:43

  2   Rubix\ML\Kernels\Distance\Euclidean::compute()
      /home/ubuntu/environment/vendor/rubix/ml/src/Classifiers/KNearestNeighbors.php:273

**Comment by andrewdalpino** [comment]
@webciter 

Can you please post your training and inference script?

Did you make sure all images are the same dimensionality?

Also using KNN on such a high-dimensional problem space (over 4 million) is probably not a good idea - refer to the [curse of dimensionality](https://en.wikipedia.org/wiki/Curse_of_dimensionality)

**Comment by andrewdalpino** [comment]
Feel free to open the issue again if/when you're ready to provide the requested info

Thank you!
