### ISSUE TITLE
Documentation is half assed and incomplete with no decent examples

### ISSUE THREAD

**Issue by kgrosvenor** [RubixML/ML#72]
Kinda been forced to use this since php-ml went down due to this projects copyright claims, but having looked at the docs it just doesn't do it the same as php-ml.  Honestly think the claims are fully BS at this point, these two libraries are wildly different. This projects attitude stinks and the documentation sucks, just putting it out there.

**Comment by andrewdalpino** [comment]
I understand your frustration @kgrosvenor but the maintainer of that package had ample opportunity to make changes that would have kept the repository up and non-infringing.

Here is a link to our documentation site https://docs.rubixml.com/en/latest/

Also we have 10 tutorials/example projects with pre-cleaned datasets here https://github.com/RubixML

Also here is a section of code that was copied from Rubix ML into PHP-ML. Rubix ML on the left, PHP-ML on the right. This is an example from just 1 of the 7 files that were copied. Some of those examples even demonstrate that code 'anomalies' or idiosyncrasies were copied as well. Approximately 600 lines of code in total copied without attribution to the original author.

<img width="923" alt="Annotation 2020-05-25 014110" src="https://user-images.githubusercontent.com/18690561/82999094-25887280-9fce-11ea-9b58-a75d0aa47d50.png">

How would you suggest we improve the documentation? Let me know if you had any more questions and I'll be happy to help

**Comment by akondas** [comment]
Hey @kgrosvenor, sources of `php-ml` without contentious code are currently read-only. You can fix your build by running the command: `composer update php-ai/php-ml --lock`. If you have not downloaded the code before then the normal `require` command should work. I apologize for the problems.
