### ISSUE TITLE
Dynamic column width of Dataset string representation

### ISSUE THREAD

**Issue by andrewdalpino** [RubixML/ML#79]
String representations of dataset objects are used for previewing their contents from the terminal. When converting a Dataset object to a string, we build a table using ascii characters. The current table has fixed width columns that do not take full advantage of the terminal real estate if the dataset only contains a few columns.

```php
echo $dataset;
```

<img width="574" alt="Annotation 2020-06-19 175914" src="https://user-images.githubusercontent.com/18690561/85184774-b57cad80-b256-11ea-8be9-c11f0c0a0361.png">

This enhancement is to output a table with dynamic column widths that are tailored to the data in the column. For example, text blobs and long category names will benefit from a wider column. Both [Labeled](https://github.com/RubixML/RubixML/blob/master/src/Datasets/Labeled.php) and [Unlabeled](https://github.com/RubixML/RubixML/blob/master/src/Datasets/Unlabeled.php) datasets will require changes.

**Comment by marclaporte** [comment]
Thank you @andrewdalpino! The Tiki team will handle this one. Please keep the "good first issues" coming!

**Comment by keevBush** [comment]
![forAndrew](https://user-images.githubusercontent.com/36192217/87318332-7a555d80-c528-11ea-94a2-660c3fb28fcc.jpg)
We need to know if this result is what you want.

**Comment by andrewdalpino** [comment]
Hey @keevBush ideally we'd like the header to line up with the column and the horizontal rule ('----...-') should extend to the end of the table but you're on the right track!

Bear in mind that we only *really* want to extend the width of the column if we have too few columns to fill up the width of the terminal window. The idea is to give the user a quick preview of the contents of the dataset and if we have some column width to spare then let's use it to display more of the data (if we can).

**Comment by raphaeldealmeida** [comment]
@andrewdalpino, assign this issue to me. I have an idea of implementation. I will refactor the __toString() methods and perhaps the Console class.

**Comment by andrewdalpino** [comment]
Hey @raphaeldealmeida ... the way we've been doing it with these *public* issues is we wait until the first contributor submits a PR to assign it. We do this to give someone else the chance to submit a PR in the interim as well. Feel free to be the first to submit a PR for this issue and I'll gladly assign you!

Feel free to join us in our Telegram channel as well https://t.me/RubixML

Thank you

**Comment by andrewdalpino** [comment]
Closing this as we may use `__toString()` in a later version for something different.
