### ISSUE TITLE
Skip-Gram variable length tokens

### ISSUE THREAD

**Issue by andrewdalpino** [RubixML/ML#81]
Unlike [N-Gram](https://github.com/RubixML/RubixML/blob/master/src/Other/Tokenizers/NGram.php), the current [Skip-Gram](https://github.com/RubixML/RubixML/blob/master/src/Other/Tokenizers/SkipGram.php) tokenizer does not allow variable length tokens. This ticket is to implement a min max scheme similar to the N-Gram tokenizer such that each token is a *k-skip-n-gram*. In other words, instead of fixing *n*, the value should vary between min and max. This allows the Tokenizer to potentially generate alot more tokens from the same blob of text.

Here's a paper on skip-gram http://www.lrec-conf.org/proceedings/lrec2006/pdf/357_pdf.pdf

Also https://en.wikipedia.org/wiki/N-gram#Skip-gram

> **Note:** Not to be confused with the skip-gram version of Word2Vec.

This change requires breaking changes via the Skip-Gram constructor, however we could easily get this out before our first stable release (next month or so).

**Comment by absolutic** [comment]
Hello, could you please assign me to this issue?
Please approve if I understood correctly: for the sentence "w1 w2 w3 w4 w5" for min = 2 and max =3 and skip =1 the refactored method should produce:
array (size=10)
  0 => string 'w1 w2' (length=5)
  1 => string 'w1 w3' (length=5)
  2 => string 'w1 w2 w3' (length=8)
  3 => string 'w1 w3 w4' (length=8)
  4 => string 'w2 w3' (length=5)
  5 => string 'w2 w4' (length=5)
  6 => string 'w2 w3 w4' (length=8)
  7 => string 'w2 w4 w5' (length=8)
  8 => string 'w3 w4' (length=5)
  9 => string 'w3 w4 w5' (length=8)

And should tests and documentation for Skip-Gram be changed as part of PR with refactoring?

**Comment by andrewdalpino** [comment]
Thanks for your interest in helping us with this enhancement @absolutic!

We typically don't assign issue tickets that are open to the public but feel free to be the first to submit a pull request for this issue and while the PR is under code review it will be assigned to you. It looks like we're on the same page regarding how the tokens should be generated. We want a token between min and max terms with up to *skip* terms skipped over. Yes tests and documentation will most likely need to be updated. See our [contributing guide](https://github.com/RubixML/RubixML/blob/master/CONTRIBUTING.md) for the information regarding that.

This enhancement will *most likely* require a change to Skip Gram's constructor, therefore, we'll need to target the next major release branch (1.0.0) in that case as it will introduce a BC break.

Thanks, and let me know if you had any more questions!

**Comment by andrewdalpino** [comment]
Nice work @absolutic I left a comment on the PR regarding the CLA bot. It should be fixed now.
