### ISSUE TITLE
Implement n-gram tokenizer

### ISSUE THREAD

**Issue by andrewdalpino** [RubixML/ML#9]
**Is your feature request related to a problem? Please describe.**
For natural language processing tasks, Rubix engineers often use the *bag-of-words* method to represent documents as fixed length feature vectors. Currently, the two tokenizers (Word and Whitespace) are only capable of tokenizing a single word at a time. This means that word sequence information is thrown away. We can recover some amount of sentence structure by using n-grams, however Rubix currently does not offer n-gram support.

**Describe the solution you'd like**
Implement an n-gram tokenizer with ability to choose word length and separator.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by andrewdalpino** [comment]
Implemented as NGram tokenizer

**Comment by drupol** [comment]
I also made a package for NGrams, fully tested: https://packagist.org/packages/drupol/phpngrams
