### ISSUE TITLE
Issue using numeric strings as labels

### ISSUE THREAD

**Issue by batata004** [RubixML/ML#91]
Hi,

I have this pretty simple code below:

```
$dataset = Labeled::fromIterator(new CSV("teste1.csv",true));
$dataset->apply(new NumericStringConverter());

[$training, $testing] = $dataset->stratifiedSplit(0.8);

$estimator = new KNearestNeighbors(3);

$estimator->train($training);
```

My `teste1.csv` file is like this:

```
AAA,BBB,OUTPUT
0,1,0
1,1,0
2,1,0
0,4,0
1,3,0
...
```

You can see that I used `NumericStringConverter` because `KNearestNeighbors`, with the default kernel, expects continuous values at the samples/columns AND also expects categorical values at the label. 

By default CSV imports everything as strings, so to use `KNearestNeighbors` with the default kernel, I need to convert the samples to numeric values using `NumericStringConverter`.

And it looks like `KNearestNeighbors` only affects the sample/columns, not the labels. How do I know that? Simple. I executed the code below:

```
$dataset = Labeled::fromIterator(new CSV("teste1.csv",true));
$dataset->apply(new NumericStringConverter());

$dataset->transformLabels(

	function ($value){
	
		var_dump($value);
		return $value;
		
	}
	
);
```

The output is something like:

```
string(1) "0"
string(1) "0"
string(1) "0"
string(1) "0"
string(1) "0"
string(1) "1"
string(1) "1"
string(1) "1"
```

You see? `NumericStringConverter` didnt affect labels, which means they are still strings, not numbers. AND THAT'S GREAT because `KNearestNeighbors` expects strings at labels. So everything looks fine, right? No, because if I run the code at the top of this thread, it will throw this error:

`<b>Fatal error</b>:  Uncaught InvalidArgumentException: Classifiers require categorical labels, continuous given. in Z:\htdocs\ia-classificacao\vendor\rubix\ml\src\Specifications\LabelsAreCompatibleWithLearner.php:25`

Really weird right? Since the data type of the LABELS is string (as proven above), why is Rubix ML complaning about it being continuous? Anyway, to solve this bug I ended up using `transformLabels` (prior to training) to change all "0" to "no" and all "1" to "yes", and it works fine. For some reason, even if the labels have numbers as strings, Rubix ML will treat them as numbers (which it should not be doing IMHO).

**Comment by andrewdalpino** [comment]
Hi Gil! This is actually due to silent behavior of PHP. I've documented this behavior here https://docs.rubixml.com/en/latest/datasets/labeled.html

> Since PHP silently converts integer strings (ex. '1') to integers in some circumstances, you should not use integer strings to denote class labels. Instead, use an appropriate non-integer string class label such as first or second.

The `stratifiedSplit()` method is one of those circumstances where this matters

**Comment by batata004** [comment]
Awesome!!!!
