### ISSUE TITLE
Installation error: [InvalidArgumentException] could not find a version of package rubix/ml matching your minimum stability

### ISSUE THREAD

**Issue by najiagul** [RubixML/ML#93]
Last time I tried setting up RubixMl on macOS, I got this error regarding not matching my minimum-stability. I was later able to install it after setting up "minimum-stability:dev" in composer.json. 
![rubixml1](https://user-images.githubusercontent.com/51270647/88460565-8fca7000-ceb6-11ea-8748-c384cf0688bc.PNG)

Now I'm trying to set up RubixMl on a windows machine and I get the same error again.
So far I've tried it with 'composer require rubix/ml:dev-master' and 'composer require rubix/ml:"*" and I'm still not able to successfully install.
![rubixml2](https://user-images.githubusercontent.com/51270647/88460582-b5577980-ceb6-11ea-9160-7ae3e5151422.PNG)

I might be missing something or doing something wrong. Can someone help me on this?

**Comment by ghost** [comment]
@najiagul try this `composer.json`:
```
{
    "require": {
        "rubix/ml": "dev-master"
    }
}
```
I hope this helps.

**Comment by andrewdalpino** [comment]
Hi @najiagul!

This is because we haven't released a stable version number yet (soon though)

You can either require a specific version in your `composer.json` file such as `0.1.0-rc5` or `dev-master` or you could lower your project's stability requirements to `dev`

```json
    "minimum-stability": "dev"
```

making sure you are using proper json notation (the example you gave was incorrect)

Let me know if you need any more help getting started!

**Comment by najiagul** [comment]
Thanks for the responses! 

This is what I modified in my composer.json 
![rubixml3](https://user-images.githubusercontent.com/51270647/88475545-488dbf00-cf4a-11ea-903b-9da8eb9effe4.PNG)
It still gave the same error
I then lowered the stability to dev in my composer.lock
![rubixml4](https://user-images.githubusercontent.com/51270647/88475554-72df7c80-cf4a-11ea-839c-e4d48f194c49.PNG)
This doesn't solve the issue either

**Comment by andrewdalpino** [comment]
Hmmmm interesting @najiagul ... are you able to create one of the example projects with composer?

**Comment by najiagul** [comment]
@andrewdalpino  I just tried the Housing Price Predictor and it was created very smoothly.

**Comment by andrewdalpino** [comment]
If you were able to install the project with no issues, that signals to me that there is something in your composer configuration that is preventing you from installing the package. Since you were able to install the Housing example, could you use the composer.json file from that project as a template for your other projects?

**Comment by najiagul** [comment]
Yes I am using that file now and it works just as fine. Thanks a lot!

**Comment by BlackbitDevs** [comment]
@andrewdalpino Do you have any plans when to release a stable version? Currently you could require `rubix/ml` with a version constraint like `*@dev` to not having to set the minimum stability to `dev` for all project dependencies. But in our case we have a plugin which uses `rubix/ml` for some AI features. Assume this plugin is named `example/plugin` then you cannot require `"example/plugin": "*@dev"` in a project - this will not work as long as you do not set `minimum-stability` to `dev`. Same for `dev-master`. See https://github.com/composer/composer/issues/1478 for more details.
So while it currently is possible to include `rubix/ml` as a project dependency, it is impossible for libraries / plugins which use `rubix/ml`as a dependency to provide stabe versions.

**Comment by andrewdalpino** [comment]
Hey @BlackbitNeueMedien yes we are currently in the release candidate stage and plan to release 0.1.0 either in the next release or the month after. And yes we are aware of this constraint on packages requiring Rubix ML while we stabilize our public API. There is a slight chance that your plugin would break by upgrading if we did not have this constraint in place so it's for your benefit in the end.

Thanks for the question! Feel free to join our channel on Telegram https://t.me/RubixML

**Comment by andrewdalpino** [comment]
We are now in stable mode!
